// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqmnIBzqw2_M5e0JuYaYFGlK2QW9n_LGc',
    appId: '1:571943531270:web:27a436cdafa20a19d62487',
    messagingSenderId: '571943531270',
    projectId: 'crudriverpod-c9f81',
    authDomain: 'crudriverpod-c9f81.firebaseapp.com',
    storageBucket: 'crudriverpod-c9f81.appspot.com',
    measurementId: 'G-GLZGZ1TW9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGIg8E_VzNyP0f8A4onKEu-2l76qUekLo',
    appId: '1:571943531270:android:a7232463196667fbd62487',
    messagingSenderId: '571943531270',
    projectId: 'crudriverpod-c9f81',
    storageBucket: 'crudriverpod-c9f81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRfvCC7yW7DyKPXQ3Jm5SNv91_a2_HFFA',
    appId: '1:571943531270:ios:d29c6a8677bd1825d62487',
    messagingSenderId: '571943531270',
    projectId: 'crudriverpod-c9f81',
    storageBucket: 'crudriverpod-c9f81.appspot.com',
    iosBundleId: 'com.expense.expoProject',
  );
}
